name: Deploy Yahoo MCP to GCP

on:
  push:
    branches:
      - main 
jobs:
   build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker for Artifact Registry
        run:  gcloud auth configure-docker australia-southeast1-docker.pkg.dev
        
      - name: Build Docker image
        run: |
          docker build -t australia-southeast1-docker.pkg.dev/anna-platform/yahoo-mcp/yahoo-mcp-image:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push australia-southeast1-docker.pkg.dev/anna-platform/yahoo-mcp/yahoo-mcp-image:latest

      - name: Deploy new image to Cloud Run Service
        run: |
          gcloud run deploy yahoo-mcp \
            --image australia-southeast1-docker.pkg.dev/anna-platform/yahoo-mcp/yahoo-mcp-image:latest \
            --region australia-southeast1 \
            --platform managed \
            --project anna-platform \
            --allow-unauthenticated